### ISSUE TITLE
Never show someone's password

### ISSUE THREAD

**Issue by kagaramag** [code-gurus/nisisi-backend#24]
@kodek-sleuth @cop1fab cop1fab
- Never show someone's password

![image](https://user-images.githubusercontent.com/10960862/73254169-9063a180-41c6-11ea-8722-317935c425e7.png)

- In this object, we don't need "generate"

```
{ 
  ...
  "token": {
    generate: "token-code"
  }
}
```

better to make it like this
```
{ 
  ...
  "token": "token-code"
}
```
- Frontend does not need the **status code** to be returned in the **response object**

**Comment by kodek-sleuth** [comment]
Fixed
