### ISSUE TITLE
DB Connection Error handling

### ISSUE THREAD

**Issue by kagaramag** [code-gurus/nisisi-backend#30]
I think, we can't say every time everything will be okay, what happens when the app does not connect to the database?

![image](https://user-images.githubusercontent.com/10960862/74092667-e93d0f00-4acf-11ea-8f60-bc7fec61ffac.png)

Like for example for this case,
![image](https://user-images.githubusercontent.com/10960862/74092681-243f4280-4ad0-11ea-8af7-d337a81fe3be.png)
DB Server wasn't responding, and I couldn't know what's going on.

**Comment by kodek-sleuth** [comment]
Bug fix is currently up
